packages:
  - packages/*
allowBuilds:
  esbuild: set this to true or false
  sharp: set this to true or false
  workerd: set this to true or false
minimumReleaseAgeExclude:
  - '@pokit/core@0.6.0'
  - '@pokit/terminal@0.6.0'
