/**
 * Build Script: Compile Markdown Content to Static Module
 *
 * This script reads markdown files at build time and compiles them
 * into a static TypeScript module that can be imported in edge
 * environments like Cloudflare Workers.
 *
 * Usage:
 *   bun run scripts/build-content.ts
 *
 * Output:
 *   src/generated/content.ts - Static module with all content
 */

import { join } from "path";
import { z } from "zod";
import { fileMarkdown } from "@piqit/resolvers";

const contentDir = join(import.meta.dir, "../public/content");
const outputDir = join(import.meta.dir, "../src/generated");

// =============================================================================
// Define Collections (same as server.ts)
// =============================================================================

const postsResolver = fileMarkdown({
  base: join(contentDir, "posts"),
  path: "{year}/{slug}.md",
  frontmatter: z.object({
    title: z.string(),
    tags: z.array(z.string()),
    author: z.string(),
  }),
  body: { html: true, headings: true, raw: true },
});

const workPackagesResolver = fileMarkdown({
  base: join(contentDir, "work"),
  path: "{status}/wp-{priority}-{name}.md",
  frontmatter: z.object({
    category: z.string(),
    size: z.string(),
  }),
  body: { html: true, headings: true, raw: true },
});

// =============================================================================
// Compile Content
// =============================================================================

console.log("Compiling content...");

// Resolve all posts - cast to any for build-time usage
const posts = await (postsResolver as any).resolve({
  scan: {},
  filter: {},
  select: ["params.*", "frontmatter.*", "body.*"],
});

console.log(`  Found ${posts.length} posts`);

// Resolve all work packages - cast to any for build-time usage
const workPackages = await (workPackagesResolver as any).resolve({
  scan: {},
  filter: {},
  select: ["params.*", "frontmatter.*", "body.*"],
});

console.log(`  Found ${workPackages.length} work packages`);

// =============================================================================
// Generate Output Module
// =============================================================================

const output = `/**
 * Auto-generated content module
 * 
 * DO NOT EDIT - This file is generated by scripts/build-content.ts
 * 
 * Generated at: ${new Date().toISOString()}
 */

// =============================================================================
// Type Definitions
// =============================================================================

export interface Post {
  params: {
    year: string;
    slug: string;
  };
  frontmatter: {
    title: string;
    tags: string[];
    author: string;
  };
  body: {
    raw: string;
    html: string;
    headings: Array<{ depth: number; text: string; slug: string }>;
  };
}

export interface WorkPackage {
  params: {
    status: string;
    priority: string;
    name: string;
  };
  frontmatter: {
    category: string;
    size: string;
  };
  body: {
    raw: string;
    html: string;
    headings: Array<{ depth: number; text: string; slug: string }>;
  };
}

// =============================================================================
// Content Data
// =============================================================================

export const posts: Post[] = ${JSON.stringify(posts, null, 2)};

export const workPackages: WorkPackage[] = ${JSON.stringify(workPackages, null, 2)};
`;

// Ensure output directory exists
await Bun.write(join(outputDir, ".gitkeep"), "");

// Write the generated module
const outputPath = join(outputDir, "content.ts");
await Bun.write(outputPath, output);

console.log(`\nGenerated: ${outputPath}`);
console.log("Done!");
